### ISSUE TITLE
支持service下 截屏录屏 其他app的吗

### ISSUE THREAD

**Issue by lovedabaozi** [SMask/ScreenCaptureLibrary_Android#1]
能否实现 截屏录屏其他应用的内容 保存上报服务等

**Comment by SMask** [comment]
可以截屏和录屏其他应用。
但是那种设置了特殊权限的没试过。。。你可以跑Demo试下。。

**Comment by lovedabaozi** [comment]
你好，我看你这个demo 在其他应用没法触发截屏或者录屏呀？我打开这个demo 切到另一个应用 此时我该怎么截屏或者录屏这个新的应用的信息，谢谢答疑

**Comment by SMask** [comment]
呃。。在当前App开始录屏，然后切到其他App，再切回来结束录屏，是可以都录下来的。
如果说要在其他App界面触发的话。
试试悬浮窗？通知栏按钮？或者AccessibilityService？
当时研究这个的时候，产品需求就是当前App录屏。。。你这种情况没考虑过= =
不过应该也是可以实现的。。
