### ISSUE TITLE
更换视频保存位置报错

### ISSUE THREAD

**Issue by liuhuan0225** [SMask/ScreenCaptureLibrary_Android#2]
目前demo保存位置在app的data下 我想保存在相册中 或者是其他位置 即报错

**Comment by SMask** [comment]
Android Q的分区存储问题。
直接往外部存储写入文件会报错的。
可以先保存在应用内部存储，然后通过MediaStore插入Uri，复制到外部存储中。
具体 你可以看看我写的ShareLibrary_Android-FileUtils里面的方法。
https://github.com/SMask/ShareLibrary_Android/blob/master/app/src/main/java/com/mask/sharelibrary/FileUtils.java

**Comment by SMask** [comment]
看了一下源码 
结合下面两个方法应该也能设置保存路径。
ContentResolver.openFileDescriptor(Uri uri, String mode)
MediaRecorder.setOutputFile(FileDescriptor fd) 
这样能省掉复制那一步。
