### ISSUE TITLE
连续截图时失败！频率100ms

### ISSUE THREAD

**Issue by moxiaolongx0** [SMask/ScreenCaptureLibrary_Android#3]
isImageAvailable = true;这个属性只有创建截图时修改可用，在一次截图后下次截图时不会变为true，是否逻辑错误

**Comment by SMask** [comment]
imageReader.setOnImageAvailableListener 回调里面会把 isImageAvailable 置为 true
当时做的时候没考虑快速截图的问题，只是考虑手动点击的情况。
这个布尔值其实可有可无，删掉也不影响。

**Comment by SMask** [comment]
你想做快速连续截图的话，可以试着修改一下ImageReader相关的方法。看看可不可以实现
