### ISSUE TITLE
录屏

### ISSUE THREAD

**Issue by JonsonHI** [SMask/ScreenCaptureLibrary_Android#4]
/**
     * 开始 屏幕录制
     *
     * @param callback callback
     */
    public void startMediaRecorder(MediaRecorderCallback callback) {
//        if (mediaProjectionService == null) {
//            callback.onFail();
//            return;
//        }
        mediaProjectionService.startRecording(callback);
    }

感谢您的DEMO  请帮忙看下
mediaProjectionService 为空直接返回了  什么问题呢

**Comment by SMask** [comment]
mediaProjectionService 为 null 不返回不就空指针崩溃了么。。。
我这个Demo里面是需要先启动服务，然后才能截屏/录屏

**Comment by JonsonHI** [comment]
> mediaProjectionService为null不返回不就空指针崩溃了么。。。
> 我这个Demo里面是需要先启动服务，然后才能截屏/录屏

麻烦告诉下 怎么启动服务  因为我不是专业安卓

**Comment by SMask** [comment]
![image](https://user-images.githubusercontent.com/17330748/105483195-72028a00-5ce4-11eb-967a-56349165134e.png)
Demo里面 MediaProjectionHelper 类 startService方法
