### ISSUE TITLE
这个库可以录声音吗?我在我的手机上录了怎么没有声音?

### ISSUE THREAD

**Issue by zhugefubin** [SMask/ScreenCaptureLibrary_Android#6]
这个库可以录声音吗?我在我的手机上录了怎么没有声音?

**Comment by SMask** [comment]
没有录制声音
想录制声音的话，可以在 `MediaProjectionService.createMediaRecorder` 里给 `MediaRecorder` 配置录制音频的相关设置

**Comment by zhugefubin** [comment]
哦,我以为你忘了写了,刚给你pull requests了一个,(●'◡'●)

**Comment by Jimmy-Min** [comment]
Hi, 我想问一下录制系统内的声音有没有什么解决方案，不要麦克风的声音
