### ISSUE TITLE
卡顿

### ISSUE THREAD

**Issue by chenxiaofei910714** [SMask/ScreenCaptureLibrary_Android#8]
我用了你的demo在点击的那一瞬间内存暴涨，有些卡顿，录屏非得需要开启Service？我看到MediaRecorder.start()开启执行，有的人在开启异步线程执行，你的没有，MediaRecorder执行耗时？

**Comment by SMask** [comment]
我这边测试设备有限
用AndroidStudio的Profiler在华为VRD-W10平板和小米8上测试，没有复现你说的内存暴涨情况，卡顿也没有出现。
可以的话，你得具体在你的设备上排查一下是什么原因导致的。
录屏开启前台Service是我这边产品需求原因，你也可以尝试不开启。
你也可以尝试子线程调用mediaRecorder.start测试一下还会不会卡顿。

Google官方也有录屏的Demo，你也可以参考一下。
https://github.com/android/media-samples/tree/main/ScreenCapture
